export const categories = [
  { value: 0, label: 'Кафе' },
  { value: 1, label: 'Рестораны' },
  { value: 2, label: 'Кофе и выпечка' },
  { value: 3, label: 'Бары' },
  { value: 4, label: 'Театры' },
  { value: 5, label: 'Культура' },
  { value: 6, label: 'Пешие прогулки' },
  { value: 7, label: 'Шоппинг' },
  { value: 8, label: 'Активный отдых' },
  { value: 9, label: 'Кино и шоу' },
  { value: 10, label: 'Развлечения' },
  { value: 11, label: 'Временные события' },
  { value: 12, label: 'Дворы и парадные' },
  { value: 13, label: 'Культовые места' },
  { value: 14, label: 'Коворки' },
  { value: 15, label: 'Однодневные путешествия' },
]